NN:
  # # Linear Model
  input_dim: 6
  output_dim: 1
  hidden_dim: 528
  n_layers: 4
  dropout: 0.01

  # Training
  batch_size: 5000
  split : 1000
  epochs: 10000
  lr: 0.001
  default_length : 978

  in_channels : 8
  hidden_channels : 128
  out_channels : 1
  kernel_size : 3