NN:
  # # Linear Model
  input_dim: 6
  output_dim: 1
  hidden_dim: 96
  n_layers: 5
  dropout: 0.05

  # Training
  batch_size: 5000
  split : 1000
  epochs: 500
  lr: 0.0002
  default_length : 978

  in_channels : 8
  hidden_channels : 128
  out_channels : 1
  kernel_size : 3