NN:
  # # Linear Model
  input_dim: 6
  output_dim: 1
  hidden_dim: 624
  n_layers: 3
  dropout: 0.00
  weight_decay: 0.0001

  # Training
  batch_size: 5000
  split : 1000
  epochs: 10000
  lr: 0.0002
  default_length : 978

  in_channels : 8
  hidden_channels : 128
  out_channels : 1
  kernel_size : 3